# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awssume < Formula
  desc "Go package to switch between AWS IAM Roles"
  homepage "https://github.com/gkze/awssume"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gkze/awssume/releases/download/v0.2.2/awssume_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "69202cb5b793b97eb022fe05d48de9907cdee36f56c2cef8761bd55d9d1ab1ef"

      def install
        bin.install "awssume"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkze/awssume/releases/download/v0.2.2/awssume_0.2.2_Linux_x86_64.tar.gz"
      sha256 "40396fa2e5ba31cbf724e316f24180519da2a849bb01af8ec5e876654513f1fe"

      def install
        bin.install "awssume"
      end
    end
  end

  test do
    system  "#{bin}/awssume -v"
  end
end
