# This file was generated by GoReleaser. DO NOT EDIT.
class Awssume < Formula
  desc "Go package to switch between AWS IAM Roles"
  homepage "https://github.com/gkze/awssume"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gkze/awssume/releases/download/v0.1.2/awssume_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "86e4773de4e067e2e83702c21cd86e5d864cc7888598dbff8e5a77cbf9242092"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/gkze/awssume/releases/download/v0.1.2/awssume_0.1.2_Linux_x86_64.tar.gz"
    sha256 "1a3a0190d9027bb1ac55d9a05d181a189697095690c1cd6f887c04e3da61e1ce"
  end

  def install
    bin.install "awssume"
  end

  test do
    system  "#{bin}/awssume -v"
  end
end
