# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emojictl < Formula
  desc "Manage your emojis"
  homepage "https://github.com/gkze/emojictl"
  version "0.1.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/gkze/emojictl/releases/download/v0.1.2/emojictl_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "759d967b01891be9b9618bdb8ecb7420dfda2f993d3d449ffb676e589fab8848"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/gkze/emojictl/releases/download/v0.1.2/emojictl_0.1.2_Linux_x86_64.tar.gz"
    sha256 "d8f5b52e25209d3dd9424481c5487464108232ec01aa0f83908b1ea89d41ed44"
  end

  def install
    bin.install "emojictl"
  end

  test do
    system  "#{bin}/emojictl -v"
  end
end
