# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emojictl < Formula
  desc "Manage your emojis"
  homepage "https://github.com/gkze/emojictl"
  version "0.1.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/gkze/emojictl/releases/download/v0.1.1/emojictl_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "4d4de06de170bd12267c31c19afd76cf2ef455afa5076fe64d3e35375998be0c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/gkze/emojictl/releases/download/v0.1.1/emojictl_0.1.1_Linux_x86_64.tar.gz"
    sha256 "dfe5baed0aa8ad3e072f50583d66001006d617ad8b50ba7482c945bcd8ac72f7"
  end

  def install
    bin.install "emojictl"
  end

  test do
    system  "#{bin}/emojictl -v"
  end
end
