# This file was generated by GoReleaser. DO NOT EDIT.
class Stars < Formula
  desc "Explore your Github stars"
  homepage "https://github.com/gkze/stars"
  url "https://github.com/gkze/stars/releases/download/v0.4.15/stars_0.4.15_Darwin_x86_64.tar.gz"
  version "0.4.15"
  sha256 "2685c22776ed3018ef88f82372e647082dd8874c210118d1eefa188ad895cde8"

  def install
    bin.install "stars"
  end

  test do
    system  "#{bin}/stars -v"
  end
end
