# This file was generated by GoReleaser. DO NOT EDIT.
class Stars < Formula
  desc "Explore your Github stars"
  homepage "https://github.com/gkze/stars"
  version "0.6.17"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gkze/stars/releases/download/v0.6.17/stars_0.6.17_Darwin_x86_64.tar.gz"
    sha256 "f05899ac504b62fbf35a3ba0c6eb3acf5b050653b1d7c7c833ddd1ea0622dbf1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gkze/stars/releases/download/v0.6.17/stars_0.6.17_Linux_x86_64.tar.gz"
      sha256 "3ee7f64d6ecf8aead1b3008901a8f4256589000c46a26bed324799e03cb72e7c"
    end
  end

  def install
    bin.install "stars"
  end

  test do
    system  "#{bin}/stars -v"
  end
end
